# Generated by Django 5.2.17 on 2026-10-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_personref_post_unit_supervisor_invited'),
        ('quizzes', '0002_quiz_grade_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('sat_on', models.DateField(help_text='The day the paper is sat; the attempts are dated then')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='quizzes.quiz')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'paper quizzes',
                'ordering': ['quiz', '-sat_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2)),
                ('items', models.JSONField(default=list)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='paperquizzes.paperquiz')),
            ],
            options={
                'ordering': ['paper', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PaperScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cells', models.JSONField(default=list, help_text='What was keyed for each question, in printed order')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_script', to='quizzes.attempt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='paperquizzes.paperquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_scripts', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='paperquizzes.paperversion')),
            ],
            options={
                'ordering': ['paper', 'student'],
            },
        ),
        migrations.AddConstraint(
            model_name='paperversion',
            constraint=models.UniqueConstraint(fields=('paper', 'label'), name='paper_version_label_once'),
        ),
        migrations.AddConstraint(
            model_name='paperscript',
            constraint=models.UniqueConstraint(fields=('paper', 'student'), name='paper_script_once'),
        ),
    ]
