# Generated by Django 5.2.17 on 2026-10-06 15:09

import core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import lti.models
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_first_attempts'),
        ('courses', '0006_completion_expiry_and_reference'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=64, unique=True)),
                ('private_pem', core.fields.EncryptedTextField(editable=True, help_text='The private key, encrypted with the application key')),
                ('public_jwk', models.JSONField(help_text='The public key as published at the JWKS address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Signs new messages')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('client_id', models.CharField(default=lti.models.new_client_id, help_text="Given to the tool's maker", max_length=120, unique=True)),
                ('deployment_id', models.CharField(default='1', help_text="Given to the tool's maker", max_length=120)),
                ('oidc_login_url', models.URLField(help_text="The tool's login initiation address")),
                ('launch_url', models.URLField(help_text='Where a launch lands in the tool (target link)')),
                ('deep_linking_url', models.URLField(blank=True, help_text='Where teaching staff choose content in the tool; empty if it has none')),
                ('redirect_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='Further addresses the tool may ask launches to be sent to', size=None)),
                ('jwks_url', models.URLField(blank=True, help_text="The tool's public key set")),
                ('public_key', models.TextField(blank=True, help_text="Or the tool's public key, as PEM or a JWK")),
                ('share_name', models.BooleanField(default=False, help_text="Send people's names to the tool")),
                ('share_email', models.BooleanField(default=False, help_text="Send people's email addresses to the tool")),
                ('grades', models.BooleanField(default=True, help_text='The tool may post scores to the gradebook')),
                ('class_list', models.BooleanField(default=False, help_text='The tool may read the class list')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_link_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('target_url', models.URLField(blank=True, help_text="Where in the tool it opens; the tool's launch address")),
                ('custom', models.JSONField(blank=True, default=dict, help_text='Custom values the tool asked for')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_link', to='courses.contentitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='lti.tool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('score_maximum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Relative weight in the coursework; 0 shows the column without counting it', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.gradecategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_line_items', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='lti.placement')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='lti.tool')),
            ],
            options={
                'ordering': ['site', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('resource_link', 'Open a placed tool'), ('deep_linking', 'Choose content in a tool')], max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, help_text='Deep linking: content came back', null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lti.placement')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lti.tool')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=list, size=None)),
                ('expires_at', models.DateTimeField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lti.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(default=lti.models.new_sub, max_length=64, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personref')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='lti.tool')),
            ],
        ),
        migrations.CreateModel(
            name='UsedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('value', models.CharField(max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lti.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_given', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('score_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('activity_progress', models.CharField(max_length=20)),
                ('grading_progress', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(help_text='When the tool says the score was given')),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lti.lineitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_scores', to='people.personref')),
            ],
            options={
                'unique_together': {('line_item', 'person')},
            },
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('jwks_url', ''), _negated=True), models.Q(('public_key', ''), _negated=True), _connector='OR'), name='lti_tool_has_a_key'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('score_maximum__gt', 0)), name='lti_line_item_maximum_positive'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='lti_line_item_weight_not_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='tooluser',
            unique_together={('tool', 'person')},
        ),
        migrations.AddConstraint(
            model_name='usedvalue',
            constraint=models.UniqueConstraint(fields=('tool', 'kind', 'value'), name='lti_value_used_once'),
        ),
    ]
