# Generated by Django 5.2.17 on 2026-10-05 17:22

import core.uploads
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_submission_original_name'),
        ('courses', '0004_teaching_content_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_time_percent', models.PositiveSmallIntegerField(default=0, help_text='Added to every quiz time limit, in percent')),
                ('extra_days', models.PositiveSmallIntegerField(default=0, help_text='Added to every assignment due date')),
                ('other_format', models.CharField(blank=True, help_text='Another format of material or assessment the student needs', max_length=300)),
                ('reason', models.TextField(blank=True, help_text='Why; seen only by course administrators')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['assignment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.uploads.feedback_name)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(help_text='The kind core.uploads found in the file', max_length=10)),
                ('size', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['submission', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Relative weight of the category in the coursework total', max_digits=6)),
                ('drop_lowest', models.PositiveSmallIntegerField(default=0, help_text='How many of the lowest counted items to leave out (at least one always counts)')),
                ('position', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'grade categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('is_released', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Entered by the marker'), ('rubric', 'Filled from the rubric or marking guide'), ('upload', 'Uploaded from a spreadsheet'), ('group', "The group's mark, with any individual adjustment"), ('agreed', 'Agreed after moderation')], max_length=10)),
                ('rubric_scores', models.JSONField(blank=True, default=list)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['submission', 'changed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('second_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('second_note', models.TextField(blank=True)),
                ('agreed_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrmsTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted by the SRMS'), ('locked', 'Already locked in the SRMS'), ('unknown', 'Not known to the SRMS')], max_length=10)),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['site', 'student', '-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('receipt', models.CharField(max_length=20, unique=True)),
                ('content_hash', models.CharField(help_text='SHA-256 of the text and every file, in order', max_length=64)),
                ('integrity_statement', models.TextField(blank=True, help_text='The academic integrity statement the student accepted with this hand-in')),
            ],
            options={
                'ordering': ['submission', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('file', models.FileField(upload_to=core.uploads.submission_name)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['attempt', 'position'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='accepted_kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='File kinds accepted (core.uploads); empty accepts every kind a submission may be', size=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_resubmission',
            field=models.BooleanField(default=True, help_text='Work may be handed in again, until the due date, while it is not marked'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Names hidden from markers until marks are released'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that take part; empty is all', related_name='+', to='courses.sitegroup'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group',
            field=models.BooleanField(default=False, help_text='One submission per group, marked for the group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty',
            field=models.CharField(choices=[('none', 'No penalty'), ('per_day', 'A percentage for each day or part of a day late'), ('per_hour', 'A percentage for each hour or part of an hour late')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The most taken in all, in percent', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent of the maximum mark taken per day or hour', max_digits=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_files',
            field=models.PositiveSmallIntegerField(default=5, help_text='Files in one hand-in; 0 allows text only'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='moderation',
            field=models.CharField(choices=[('none', 'No moderation'), ('sample', 'A second marker checks a sample'), ('double', 'Every submission is marked twice')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='requires_integrity',
            field=models.BooleanField(default=False, help_text='The student accepts the academic integrity statement with each hand-in'),
        ),
    ]
