# Generated by Django 5.2.17 on 2026-10-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_submission_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='client_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the device says it was handed in, for work sent later from its offline queue. Server time decides lateness; this is shown to teaching staff, who may excuse it by an extension.', null=True),
        ),
    ]
