# Generated by Django 5.2.17 on 2026-10-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_marking'),
        ('courses', '0004_teaching_content_data'),
        ('people', '0001_initial'),
        ('rubrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='mark',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text="This member's adjustment to the group's mark", max_digits=6),
        ),
        migrations.AddField(
            model_name='mark',
            name='group_mark',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The group's mark before adjustment", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=list, help_text='[{"criterion": id, "level": id or null, "points": "2.00" or null, "comment": ""}]'),
        ),
        migrations.AddField(
            model_name='mark',
            name='source',
            field=models.CharField(choices=[('manual', 'Entered by the marker'), ('rubric', 'Filled from the rubric or marking guide'), ('upload', 'Uploaded from a spreadsheet'), ('group', "The group's mark, with any individual adjustment"), ('agreed', 'Agreed after moderation')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.sitegroup'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='people.personref'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extension',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='assessments.assignment'),
        ),
        migrations.AddField(
            model_name='extension',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extension',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref'),
        ),
        migrations.AddField(
            model_name='extension',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.sitegroup'),
        ),
        migrations.AddField(
            model_name='extension',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='people.personref'),
        ),
        migrations.AddField(
            model_name='extension',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackfile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_files', to='assessments.submission'),
        ),
        migrations.AddField(
            model_name='feedbackfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='courses.coursesite'),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assessments.gradecategory'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('late_penalty_percent__gte', 0), ('late_penalty_percent__lte', 100)), name='assignment_late_penalty_percentage'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('late_penalty_cap__isnull', True), models.Q(('late_penalty_cap__gte', 0), ('late_penalty_cap__lte', 100)), _connector='OR'), name='assignment_late_penalty_cap_percentage'),
        ),
        migrations.AddField(
            model_name='markversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markversion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_versions', to='assessments.submission'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='agreed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderation',
            name='first_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='second_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='assessments.submission'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='srmstransfer',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='srmstransfer',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srms_transfers', to='courses.coursesite'),
        ),
        migrations.AddField(
            model_name='srmstransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srms_transfers', to='people.personref'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.submission'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessments.submissionattempt'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('group__isnull', True)), models.Q(('student__isnull', True), ('group__isnull', False)), _connector='OR'), name='extension_student_or_group'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='extension_once_per_student'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('assignment', 'group'), name='extension_once_per_group'),
        ),
        migrations.AddConstraint(
            model_name='gradecategory',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='grade_category_name_once'),
        ),
        migrations.AddConstraint(
            model_name='gradecategory',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='grade_category_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='submissionattempt',
            constraint=models.UniqueConstraint(fields=('submission', 'number'), name='submission_attempt_number_once'),
        ),
    ]
