# Generated by Django 5.2.17 on 2026-10-05 17:40

import certificates.models
import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='The same in every version', max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('heading', models.CharField(default='Certificate of Completion', max_length=160)),
                ('body', models.TextField(help_text='Paragraphs apart by a blank line, **bold**, fields in double braces such as {{full_name}}')),
                ('signatory_name', models.CharField(blank=True, max_length=120)),
                ('signatory_title', models.CharField(default='Principal', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('issued_on', models.DateField()),
                ('completed_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('values', models.JSONField(help_text='Every field as it went into the certificate')),
                ('file', models.FileField(upload_to=certificates.models.certificate_name)),
                ('sha256', models.CharField(help_text='Fingerprint of the PDF as issued', max_length=64)),
                ('check_code', core.fields.EncryptedTextField(editable=True, help_text='Printed on the certificate for checking it')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.completion')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='people.personref')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(max_length=40)),
                ('matched', models.BooleanField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['source_ip', 'at'], name='certcheck_ip_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='one_certificate_template_version'),
        ),
    ]
