# Generated by Django 5.2.17 on 2026-10-06 15:47

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=40, unique=True)),
                ('public_jwk', models.JSONField(help_text='The public key as a JSON Web Key, as published')),
                ('private_pem', core.fields.EncryptedTextField(editable=True, help_text='The private key (PKCS #8), encrypted with FIELD_ENCRYPTION_KEY')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='No longer signs; still checks', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BadgeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.UUIDField(help_text="The credential's id is urn:uuid:<this>", unique=True)),
                ('jwt', models.TextField(help_text='The signed credential, as the holder downloads it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='certificates.certificate')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='certificates.signingkey')),
            ],
        ),
    ]
