# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='in_summary',
            field=models.BooleanField(default=False, help_text="Held for the person's daily summary email instead of an email of its own"),
        ),
        migrations.AddField(
            model_name='notification',
            name='summarised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('info', 'Information'), ('approval', 'Action required'), ('alert', 'Alert'), ('mark', 'Marks and feedback'), ('reminder', 'Reminders before due dates'), ('receipt', 'Receipts for work handed in')], default='info', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Information'), ('approval', 'Action required'), ('alert', 'Alert'), ('mark', 'Marks and feedback'), ('reminder', 'Reminders before due dates'), ('receipt', 'Receipts for work handed in')], max_length=20)),
                ('email', models.CharField(choices=[('instant', 'An email for each'), ('daily', 'One daily summary email'), ('off', 'No email')], default='instant', max_length=10)),
                ('push', models.BooleanField(default=False, help_text='Phone push; kept for when push arrives (item 4.04)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='notification_preference_once')],
            },
        ),
    ]
