# Generated by Django 5.2.17 on 2026-10-06 15:29

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_preferences_and_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('info', 'Information'), ('approval', 'Action required'), ('alert', 'Alert'), ('mark', 'Marks and feedback'), ('reminder', 'Reminders before due dates'), ('receipt', 'Receipts for work handed in'), ('announcement', 'Course announcements')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('info', 'Information'), ('approval', 'Action required'), ('alert', 'Alert'), ('mark', 'Marks and feedback'), ('reminder', 'Reminders before due dates'), ('receipt', 'Receipts for work handed in'), ('announcement', 'Course announcements')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push',
            field=models.BooleanField(default=False, help_text="Also a push notice to the person's installed app (4.04)"),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', core.fields.EncryptedTextField(editable=True, help_text="The browser's public key for this subscription")),
                ('auth', core.fields.EncryptedTextField(editable=True, help_text="The browser's authentication secret, encrypted at rest")),
                ('device', models.CharField(blank=True, help_text='Which browser and system, in words', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0, help_text='Sends that failed in a row')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-created_at'],
            },
        ),
    ]
