# Generated by Django 5.2.17 on 2026-10-05 18:00
# The plain rubric ids become links to rubrics.Rubric (item 3.09). No rubric existed before, so no id
# held could name one: the old values are dropped with the plain column.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_first_attempts'),
        ('forums', '0002_conduct_statement'),
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='rubric_id',
        ),
        migrations.RemoveField(
            model_name='participationmark',
            name='rubric_id',
        ),
        migrations.AddField(
            model_name='forum',
            name='grade_category',
            field=models.ForeignKey(blank=True, help_text='The gradebook category it counts in (item 2.28)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='assessments.gradecategory'),
        ),
        migrations.AddField(
            model_name='forum',
            name='rubric',
            field=models.ForeignKey(blank=True, help_text='Rubric to mark against, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='participationmark',
            name='rubric',
            field=models.ForeignKey(blank=True, help_text='Rubric used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rubrics.rubric'),
        ),
    ]
