# Generated by Django 5.2.17 on 2026-10-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('discovered_at', models.DateTimeField()),
                ('happened', models.CharField(blank=True, help_text='When it happened, if known', max_length=160)),
                ('summary', models.TextField(help_text='What happened')),
                ('data_affected', models.TextField(help_text='What personal data, and whose')),
                ('people_affected', models.PositiveIntegerField(blank=True, help_text='How many, if known', null=True)),
                ('minors_affected', models.BooleanField(default=False, help_text='Students under 18 are among them')),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('commissioner_told_at', models.DateTimeField(blank=True, null=True)),
                ('people_told_at', models.DateTimeField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, help_text='What has been done, and what will be')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('personal', 'Name, number or email'), ('membership', 'Courses I belong to'), ('submission', 'My submissions'), ('mark', 'My marks or feedback'), ('completion', 'Courses completed'), ('account', 'My account or roles'), ('other', 'Something else')], max_length=20)),
                ('wrong', models.TextField(help_text='What is wrong', max_length=1000)),
                ('should_be', models.TextField(help_text='What it should say', max_length=1000)),
                ('state', models.CharField(choices=[('open', 'With a course administrator'), ('corrected', 'Corrected'), ('declined', 'Not changed')], default='open', max_length=12)),
                ('due_by', models.DateField(help_text='When it should have been answered (PRIVACY_RESPONSE_DAYS after)')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('proposed', 'Waiting for a second person'), ('done', 'Disposed of'), ('cancelled', 'Cancelled')], default='proposed', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.BigIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('due_since', models.DateField(help_text='When the period ran out')),
                ('keep_reason', models.CharField(blank=True, help_text='Why it is kept after all', max_length=300)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='privacy.disposalrun')),
            ],
            options={
                'ordering': ['due_since', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text; a blank line starts a new paragraph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Empty while it is a draft', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('keep_months', models.PositiveIntegerField(blank=True, help_text='Empty when each record carries its own date', null=True)),
                ('counted_from', models.CharField(help_text='What the period is counted from, in words', max_length=160)),
                ('action', models.CharField(choices=[('delete', 'Delete'), ('review', 'Reviewed by GSA; the system removes nothing')], default='delete', max_length=12)),
                ('automatic', models.BooleanField(default=False, help_text='Disposed of every night without review (logs, not records)')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='The source of the period, or why it differs', max_length=300)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['automatic', 'name'],
            },
        ),
        migrations.AddField(
            model_name='disposalrun',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='privacy.retentionrule'),
        ),
        migrations.CreateModel(
            name='NoticeAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='privacy.privacynotice')),
            ],
            options={
                'ordering': ['-at'],
                'constraints': [models.UniqueConstraint(fields=('notice', 'user'), name='one_acknowledgement_per_notice')],
            },
        ),
        migrations.AddConstraint(
            model_name='disposalrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'proposed')), fields=('rule',), name='one_proposed_run_per_rule'),
        ),
    ]
