# Generated by Django 5.2.17 on 2026-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionrule',
            name='action',
            field=models.CharField(choices=[('delete', 'Delete'), ('review', 'Reviewed by GSA; the system removes nothing'), ('archive', 'Archived: a read-only export is kept; nothing is deleted')], default='delete', max_length=12),
        ),
    ]
