# Generated by Django 5.2.17 on 2026-10-05 16:09

import core.uploads
from django.db import migrations, models


def keep_existing_names(apps, schema_editor):
    """Files stored before this change keep their stored name as the name they download under."""
    ContentItem = apps.get_model("courses", "ContentItem")
    for row in ContentItem.objects.filter(original_name="").exclude(file="").only("id", "file"):
        row.original_name = (row.file.name or "").rsplit("/", 1)[-1][:255]
        row.save(update_fields=["original_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='original_name',
            field=models.CharField(blank=True, help_text='The name the file had when it was put up; used for downloads', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='file',
            field=models.FileField(blank=True, upload_to=core.uploads.content_name),
        ),
        migrations.RunPython(keep_existing_names, migrations.RunPython.noop),
    ]
