# Generated by Django 5.2.17 on 2026-10-05 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_contentitem_original_name'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Hidden from students until then', null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Bytes; counted against the allowance'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='licence',
            field=models.CharField(choices=[('gsa_own', "GSA's own material"), ('open_licence', 'Under an open licence'), ('fair_dealing', 'Used under fair dealing for research or private study'), ('permission_held', "Used with the owner's permission"), ('unknown', 'Not yet known')], default='gsa_own', max_length=20),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='open_licence',
            field=models.CharField(blank=True, choices=[('cc_by', 'CC BY'), ('cc_by_sa', 'CC BY-SA'), ('cc_by_nc', 'CC BY-NC'), ('cc0', 'CC0'), ('other', 'Another open licence')], help_text='Which open licence', max_length=10),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='requires_item',
            field=models.ForeignKey(blank=True, help_text='Hidden from a student until they have completed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.contentitem'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='source',
            field=models.TextField(blank=True, help_text='Where the material comes from and how to credit it'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Hidden from students while a takedown request is reviewed'),
        ),
        migrations.AddField(
            model_name='coursesite',
            name='storage_allowance_mb',
            field=models.PositiveIntegerField(blank=True, help_text="Storage for this site's files in megabytes; empty means SITE_STORAGE_ALLOWANCE_MB", null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Hidden from students until then', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_item',
            field=models.ForeignKey(blank=True, help_text='Hidden from a student until they have completed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.contentitem'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='body',
            field=models.TextField(blank=True, help_text="A page's text as cleaned HTML (courses.richtext)"),
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='courses.membership')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group',
                'ordering': ['name', 'id'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Shown only to members of these groups', related_name='+', to='courses.sitegroup'),
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Shown only to members of these groups', related_name='+', to='courses.sitegroup'),
        ),
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('structure', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False, help_text='Applied to every new site')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TakedownRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Waiting for review'), ('withdrawn', 'Item withdrawn'), ('restored', 'Item restored')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takedowns', to='courses.contentitem')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('how', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('marked', 'Marked as complete')], max_length=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.contentitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_completions', to='people.personref')),
            ],
            options={
                'unique_together': {('person', 'item')},
            },
        ),
    ]
