# Generated by Django 5.2.17 on 2026-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teaching_content_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='expires_on',
            field=models.DateField(blank=True, help_text='When the training must be renewed', null=True),
        ),
        migrations.AddField(
            model_name='completion',
            name='external_ref',
            field=models.CharField(blank=True, help_text='The reference the HRMS keeps it under; set when first reported', max_length=120),
        ),
        migrations.AddField(
            model_name='completion',
            name='how',
            field=models.CharField(choices=[('rules', "The site's completion rules were met"), ('recorded', 'Recorded by a course administrator')], default='recorded', max_length=10),
        ),
    ]
