# Generated by Django 5.2.17 on 2026-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='kind',
            field=models.CharField(choices=[('page', 'Page'), ('file', 'File'), ('link', 'Link'), ('package', 'SCORM or H5P package')], default='page', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemcompletion',
            name='how',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('marked', 'Marked as complete'), ('package', 'Completed in the package')], max_length=12),
        ),
    ]
