# Generated by Django 5.2.17 on 2026-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesite',
            name='kind',
            field=models.CharField(choices=[('academic', 'Academic course'), ('staff_development', 'Staff development'), ('open', 'Open short course for farmers and extension officers (item 5.07)')], default='academic', max_length=20),
        ),
    ]
