# Generated by Django 5.2.17 on 2026-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='kind',
            field=models.CharField(choices=[('page', 'Page'), ('file', 'File'), ('link', 'Link'), ('video', 'Video')], default='page', max_length=10),
        ),
    ]
