# Generated by Django 5.2.17 on 2026-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_contentitem_video_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='kind',
            field=models.CharField(choices=[('page', 'Page'), ('file', 'File'), ('link', 'Link'), ('package', 'SCORM or H5P package'), ('video', 'Video')], default='page', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemcompletion',
            name='how',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('marked', 'Marked as complete'), ('package', 'Completed in the package')], max_length=12),
        ),
    ]
