# Generated by Django 5.2.17 on 2026-10-06 15:05

import django.db.models.deletion
import terms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(max_length=16)),
                ('file', models.FileField(max_length=255, upload_to=terms.models.archive_name)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('records', models.PositiveIntegerField(help_text='Rows exported, all kinds together')),
                ('files', models.PositiveIntegerField(help_text='Stored files copied into the export')),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='courses.coursesite')),
            ],
            options={
                'ordering': ['-made_at'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='The SRMS term code, e.g. 2026-27-S1', max_length=16, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(help_text='Last day of teaching')),
                ('closes_on', models.DateField(help_text='Last day on which work is handed in; sites close after it')),
                ('grace_days', models.PositiveSmallIntegerField(blank=True, help_text='Days after the close date still accepted; empty: TERM_GRACE_DAYS', null=True)),
                ('source', models.CharField(choices=[('srms', 'From the SRMS'), ('local', 'Entered in the LMS')], default='local', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the nightly job closed its sites', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When every site was archived', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', 'code'],
            },
        ),
    ]
