# Generated by Django 5.2.17 on 2026-10-06 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_first_attempts'),
        ('courses', '0008_package_kind'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.CharField(choices=[('scorm12', 'SCORM 1.2'), ('scorm2004', 'SCORM 2004'), ('h5p', 'H5P')], max_length=10)),
                ('version_label', models.CharField(blank=True, help_text='As the package describes itself', max_length=80)),
                ('scos', models.JSONField(default=list, help_text='The parts a learner opens: [{"id", "title", "href", "parameters"}]')),
                ('entries', models.PositiveIntegerField(default=0, help_text='Files in the package')),
                ('unpacked_bytes', models.PositiveBigIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text="Relative weight within the site's coursework; 0 means it does not count", max_digits=5)),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='0 means no limit')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade_category', models.ForeignKey(blank=True, help_text='The gradebook category it counts in (item 2.28)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='assessments.gradecategory')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='courses.contentitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('registration', models.UUIDField(default=uuid.uuid4, help_text='The xAPI registration that ties statements to this attempt', unique=True)),
                ('is_preview', models.BooleanField(default=False)),
                ('runtime', models.JSONField(default=dict, help_text='Per part of the package: the CMI data as last committed (SCORM), or the result')),
                ('completion', models.CharField(choices=[('not_attempted', 'Not started'), ('incomplete', 'Started'), ('completed', 'Completed')], default='not_attempted', max_length=14)),
                ('success', models.CharField(choices=[('unknown', 'No result'), ('passed', 'Passed'), ('failed', 'Not passed')], default='unknown', max_length=8)),
                ('score', models.DecimalField(blank=True, decimal_places=4, help_text='As a fraction of the maximum, 0 to 1', max_digits=7, null=True)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='packages.contentpackage')),
                ('person', models.ForeignKey(blank=True, help_text='The learner; empty only for a preview by someone with no person record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_attempts', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['package', 'person', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('verb', models.CharField(max_length=300)),
                ('activity', models.CharField(help_text="The object's id (an IRI)", max_length=500)),
                ('statement', models.JSONField(help_text="The statement as stored, with the LMS's actor, id and times")),
                ('timestamp', models.DateTimeField()),
                ('stored', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='packages.packageattempt')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='packages.contentpackage')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='people.personref')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='courses.coursesite')),
            ],
            options={
                'ordering': ['-stored'],
            },
        ),
        migrations.AddConstraint(
            model_name='contentpackage',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='package_weight_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='packageattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preview', False)), fields=('package', 'person', 'number'), name='package_attempt_number'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['activity'], name='statement_activity'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['person', 'stored'], name='statement_person_stored'),
        ),
    ]
