# Generated by Django 5.2.17 on 2026-10-05 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_completion_expiry_and_reference'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, help_text='What the course covers, in a few sentences')),
                ('audience', models.CharField(blank=True, help_text='Who it is for', max_length=200)),
                ('length_hours', models.DecimalField(blank=True, decimal_places=1, help_text='About how many hours it takes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('self_enrol', models.CharField(choices=[('open', 'Anyone on the staff may join'), ('approval', 'Joining is approved by the supervisor'), ('closed', 'Not open to join; course administrators enrol people')], default='approval', max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Places; empty means no limit', null=True)),
                ('rule_all_items', models.BooleanField(default=True, help_text='Every published item completed')),
                ('rule_quizzes_passed', models.BooleanField(default=False, help_text='Every published quiz with a pass mark passed at that mark')),
                ('rule_assignment_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Every published assignment marked, and released, at least this percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('validity_months', models.PositiveSmallIntegerField(blank=True, help_text='How long a completion lasts before it must be renewed', null=True)),
                ('issue_certificate', models.BooleanField(default=True, help_text='Issue a certificate on completion')),
                ('certificate_template', models.CharField(default='completion', help_text="The certificate template's code", max_length=40)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'catalogue entries',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, help_text='The role it is for', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RequiredTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus_code', models.CharField(blank=True, help_text='Only staff of this campus', max_length=10)),
                ('unit_code', models.CharField(blank=True, help_text='Only staff of this unit', max_length=20)),
                ('post_title', models.CharField(blank=True, help_text='Only staff holding this post', max_length=160)),
                ('due_days', models.PositiveSmallIntegerField(default=30, help_text='Days from assignment to the due date')),
                ('renewal_months', models.PositiveSmallIntegerField(blank=True, help_text='Taken again this often; empty means once', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site__title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnrolmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('submitted', 'Waiting for a decision'), ('approved', 'Approved'), ('rejected', 'Not approved'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=10)),
                ('previous_state', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why the person wants to take the course')),
                ('decision_comment', models.TextField(blank=True)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, help_text='The supervisor it was sent to; empty means the course administrators decide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments_to_decide', to='people.personref')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_requests', to='people.personref')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_requests', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'submitted')), fields=('site', 'person'), name='one_open_enrolment_request')],
            },
        ),
        migrations.CreateModel(
            name='PathEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='staffdev.learningpath')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='people.personref')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('path', 'person'), name='path_joined_once')],
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='staffdev.learningpath')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_steps', to='courses.coursesite')),
            ],
            options={
                'ordering': ['path', 'position'],
                'constraints': [models.UniqueConstraint(fields=('path', 'site'), name='path_site_once'), models.UniqueConstraint(fields=('path', 'position'), name='path_position_once')],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_on', models.DateField()),
                ('due_on', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='people.personref')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staffdev.requiredtraining')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_on', 'id'],
                'constraints': [models.UniqueConstraint(fields=('requirement', 'person'), name='required_training_once_per_person')],
            },
        ),
    ]
