# Generated by Django 5.2.17 on 2026-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredtraining',
            name='hrms_id',
            field=models.PositiveIntegerField(blank=True, help_text="The HRMS's own number for a requirement it keeps", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requiredtraining',
            name='source',
            field=models.CharField(choices=[('lms', 'Kept in the LMS'), ('hrms', 'Kept in the HRMS')], default='lms', max_length=4),
        ),
    ]
