# Generated by Django 5.2.17 on 2026-10-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personref',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When the last invitation to choose a password was sent (item 1.22)', null=True),
        ),
        migrations.AddField(
            model_name='personref',
            name='post_title',
            field=models.CharField(blank=True, help_text='Post held, from the HRMS', max_length=160),
        ),
        migrations.AddField(
            model_name='personref',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="Who approves this person's staff-development enrolments; filled once the HRMS sends it", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to='people.personref'),
        ),
        migrations.AddField(
            model_name='personref',
            name='unit_code',
            field=models.CharField(blank=True, help_text='Organisational unit, from the HRMS', max_length=20),
        ),
    ]
