# Generated by Django 5.2.17 on 2026-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_personref_post_unit_supervisor_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personref',
            name='kind',
            field=models.CharField(choices=[('staff', 'Staff (HRMS employee number)'), ('student', 'Student (SRMS student number)'), ('learner', 'Learner on open courses, self-registered (item 5.07)')], max_length=10),
        ),
    ]
