# Generated by Django 5.2.17 on 2026-10-05 16:26

import django.contrib.postgres.fields
import django.db.models.deletion
import quizzes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('deadline', models.DateTimeField(blank=True, help_text='Server time after which answers are refused', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('current_page', models.PositiveSmallIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('max_score', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('needs_grading', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quiz', 'student', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('started', 'Started'), ('resumed', 'Resumed'), ('answer_saved', 'Answer saved'), ('answer_refused', 'Answer refused'), ('page_changed', 'Moved to the next page'), ('submitted', 'Submitted'), ('auto_submitted', 'Submitted automatically when time ran out'), ('marked', 'Marked by a person'), ('released', 'Result released')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quizzes.attempt')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('department_code', models.CharField(blank=True, help_text='HRMS unit code of the department that shares this bank', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='quizzes.questionbank')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quizzes.questioncategory')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'question categories',
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qtype', models.CharField(choices=[('multichoice', 'Multiple choice'), ('truefalse', 'True or false'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('shortanswer', 'Short answer'), ('numerical', 'Numerical'), ('cloze', 'Fill in the blanks'), ('essay', 'Essay'), ('file', 'File response'), ('image_label', 'Label a diagram')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('is_archived', models.BooleanField(default=False, help_text='Hidden from new quizzes; kept for past attempts')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.questionbank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizzes.questioncategory')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Type-specific settings; see quizzes.schemas')),
                ('default_mark', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('general_feedback', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=quizzes.models.question_image_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quizzes.question')),
            ],
            options={
                'ordering': ['question', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=quizzes.models.answer_file_name)),
                ('client_saved_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('fraction', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('awarded', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('auto_feedback', models.TextField(blank=True)),
                ('needs_manual', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, help_text="The marker's comment")),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quizzes.questionversion')),
            ],
            options={
                'ordering': ['attempt', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_allowed', models.PositiveSmallIntegerField(default=1, help_text='0 means unlimited')),
                ('grading_method', models.CharField(choices=[('highest', 'Highest attempt'), ('average', 'Average of attempts'), ('first', 'First attempt'), ('last', 'Last attempt')], default='highest', max_length=10)),
                ('pass_mark', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage needed to pass', max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text="Relative weight within the site's coursework", max_digits=5)),
                ('is_practice', models.BooleanField(default=False, help_text='Revision only: never counts, unlimited attempts')),
                ('is_published', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('questions_per_page', models.PositiveSmallIntegerField(default=0, help_text='0 puts every question on one page')),
                ('navigation', models.CharField(choices=[('free', 'Free: move between pages in any order'), ('sequential', 'Sequential: no going back')], default='free', max_length=10)),
                ('review_marks', models.CharField(choices=[('immediately', 'Immediately after the attempt'), ('after_close', 'After the quiz closes'), ('never', 'Never')], default='immediately', max_length=12)),
                ('review_correct', models.CharField(choices=[('immediately', 'Immediately after the attempt'), ('after_close', 'After the quiz closes'), ('never', 'Never')], default='after_close', max_length=12)),
                ('review_feedback', models.CharField(choices=[('immediately', 'Immediately after the attempt'), ('after_close', 'After the quiz closes'), ('never', 'Never')], default='immediately', max_length=12)),
                ('auto_release', models.BooleanField(default=True, help_text='Release a result as soon as it is fully marked; otherwise the lecturer releases it')),
                ('feedback_bands', models.JSONField(blank=True, default=list, help_text='Overall feedback: [{"min_percent": 80, "feedback": "..."}]')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['closes_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_minutes', models.PositiveIntegerField(default=0)),
                ('extra_attempts', models.PositiveSmallIntegerField(default=0)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Kept for the record; not shown to students', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_overrides', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quiz', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('random_count', models.PositiveSmallIntegerField(default=1)),
                ('include_subcategories', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, help_text='Random questions only from this tag', max_length=40)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='quizzes.questioncategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='quizzes.quiz')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('site__isnull', False), ('department_code', '')), models.Q(('site__isnull', True), models.Q(('department_code', ''), _negated=True)), _connector='OR'), name='question_bank_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'number'), name='question_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('default_mark__gt', 0)), name='question_default_mark_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='attempt_answer_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(('awarded__isnull', True), ('awarded__gte', 0), _connector='OR'), name='awarded_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='quiz_weight_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('pass_mark__isnull', True), models.Q(('pass_mark__gte', 0), ('pass_mark__lte', 100)), _connector='OR'), name='quiz_pass_mark_percentage'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('quiz', 'student', 'number'), name='attempt_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'in_progress')), fields=('quiz', 'student'), name='attempt_one_in_progress'),
        ),
        migrations.AddConstraint(
            model_name='quizoverride',
            constraint=models.UniqueConstraint(fields=('quiz', 'student'), name='quiz_override_once'),
        ),
        migrations.AddConstraint(
            model_name='quizslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('category__isnull', True)), models.Q(('question__isnull', True), ('category__isnull', False)), _connector='OR'), name='quiz_slot_question_or_category'),
        ),
        migrations.AddConstraint(
            model_name='quizslot',
            constraint=models.CheckConstraint(condition=models.Q(('mark__isnull', True), ('mark__gt', 0), _connector='OR'), name='quiz_slot_mark_positive'),
        ),
    ]
