# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_marking'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade_category',
            field=models.ForeignKey(blank=True, help_text='The gradebook category it counts in (item 2.28)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='assessments.gradecategory'),
        ),
    ]
