# Generated by Django 5.2.17 on 2026-10-10 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_accommodation_reason_encrypted'),
        ('courses', '0008_package_kind'),
        ('quizzes', '0002_quiz_grade_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_secure_exam',
            field=models.BooleanField(default=False, help_text="Secure exam mode (item 3.25, ADR 0045): one attempt only, enforced on the server, and the sitting's focus changes and copy/paste/right-click attempts are logged for teaching staff to review. A deterrent on a web page, not a lockdown browser or webcam proctoring (ADR 0006)."),
        ),
        migrations.AlterField(
            model_name='attemptevent',
            name='kind',
            field=models.CharField(choices=[('started', 'Started'), ('resumed', 'Resumed'), ('answer_saved', 'Answer saved'), ('answer_refused', 'Answer refused'), ('page_changed', 'Moved to the next page'), ('submitted', 'Submitted'), ('auto_submitted', 'Submitted automatically when time ran out'), ('marked', 'Marked by a person'), ('released', 'Result released'), ('focus_lost', 'Left the quiz window or tab'), ('focus_resumed', 'Returned to the quiz window or tab'), ('copy_attempted', 'Tried to copy text from the quiz page'), ('paste_attempted', 'Tried to paste into an answer'), ('context_menu_blocked', 'Tried to open the right-click menu')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('is_secure_exam', False), ('attempts_allowed', 1), _connector='OR'), name='quiz_secure_exam_one_attempt'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('is_secure_exam', False), ('is_practice', False), _connector='OR'), name='quiz_secure_exam_not_practice'),
        ),
    ]
