# Generated by Django 5.2.17 on 2026-10-05 17:23

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_grouping_groupsignup'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_to_srms', models.BooleanField(default=False, help_text='The programme makes attendance a condition')),
                ('minimum_percent', models.DecimalField(blank=True, decimal_places=2, help_text="The programme's minimum, if any", max_digits=5, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Room, laboratory, farm or plot', max_length=160)),
                ('meeting_url', models.URLField(blank=True, max_length=500, validators=[attendance.models.https_only])),
                ('recording_url', models.URLField(blank=True, help_text='Added after the class', max_length=500, validators=[attendance.models.https_only])),
                ('takes_attendance', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='For one group only (a lab or field group); empty for the whole class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.sitegroup')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('absent', 'Absent')], max_length=10)),
                ('how', models.CharField(choices=[('register', 'Marked by teaching staff'), ('check_in', 'Checked in with the code in the room'), ('closed', 'Absent when the register was closed')], max_length=10)),
                ('acted_at', models.DateTimeField(help_text="When the person acted: the phone's time for a register taken offline, else the server's")),
                ('client_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.classsession')),
            ],
            options={
                'ordering': ['session', 'student__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='class_session_order'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='attendance_once_per_session'),
        ),
    ]
