# Generated by Django 5.2.17 on 2026-10-05 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='Such as annual leave, or a course', max_length=160)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_held', to='people.personref')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends__gte', models.F('starts'))), name='delegation_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('delegate', models.F('delegator')), _negated=True), name='delegation_to_someone_else')],
            },
        ),
    ]
