# Generated by Django 5.2.17 on 2026-10-06 15:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_first_attempts'),
        ('courses', '0006_completion_expiry_and_reference'),
        ('messaging', '0001_initial'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        ('quizzes', '0002_quiz_grade_category'),
        ('rubrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('srms', 'From the SRMS course outline'), ('local', 'Added on the site')], max_length=10)),
                ('course_code', models.CharField(blank=True, help_text='SRMS outcomes: the course', max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='False once the SRMS no longer lists it; its links and evidence stay')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Local outcomes: the site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_outcomes', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.assignment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rubrics.rubriccriterion')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='insights.outcome')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_links', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['outcome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('programme_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Programmes the offering belongs to, when the SRMS sends them', size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='courses.coursesite')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('missed_work', 'Missed work'), ('falling_marks', 'Falling marks'), ('no_visits', 'No visits')], max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('evidence', models.JSONField(default=list, help_text='[{"what": "...", "when": "ISO date or null"}]')),
                ('evidence_key', models.CharField(help_text='What the evidence is about; the same evidence never raises a second alert', max_length=64)),
                ('raised_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('open', 'New'), ('acknowledged', 'Seen'), ('acted', 'Acted on'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='What was done, or why it was dismissed')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.conversation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='courses.coursesite')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('site', 'student', 'kind', 'evidence_key'), name='alert_evidence_once')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('missed_work', 'Missed work'), ('falling_marks', 'Falling marks'), ('no_visits', 'No visits')], max_length=20, unique=True)),
                ('threshold', models.PositiveSmallIntegerField(help_text='Missed work: pieces of work missed. Falling marks: percentage points fallen. No visits: days with nothing done on the course.')),
                ('window_days', models.PositiveSmallIntegerField(default=28, help_text='Missed work: only work due in this many days counts. Falling marks: the latest mark must be this recent. Not used for no visits.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold__gt', 0)), name='alert_rule_threshold_set')],
            },
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'srms'), models.Q(('course_code', ''), _negated=True), ('site__isnull', True)), models.Q(('source', 'local'), ('site__isnull', False)), _connector='OR'), name='outcome_source_owner'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'srms')), fields=('course_code', 'code'), name='outcome_srms_code_once'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'local')), fields=('site', 'code'), name='outcome_local_code_once'),
        ),
        migrations.AddConstraint(
            model_name='outcomelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment__isnull', False), ('question__isnull', True), ('criterion__isnull', True)), models.Q(('assignment__isnull', True), ('question__isnull', False), ('criterion__isnull', True)), models.Q(('assignment__isnull', True), ('question__isnull', True), ('criterion__isnull', False)), _connector='OR'), name='outcome_link_one_target'),
        ),
        migrations.AddConstraint(
            model_name='outcomelink',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('site', 'outcome', 'assignment'), name='outcome_link_assignment_once'),
        ),
        migrations.AddConstraint(
            model_name='outcomelink',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('site', 'outcome', 'question'), name='outcome_link_question_once'),
        ),
        migrations.AddConstraint(
            model_name='outcomelink',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion__isnull', False)), fields=('site', 'outcome', 'criterion'), name='outcome_link_criterion_once'),
        ),
    ]
