# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_teaching_content_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('scored', 'Rubric with points'), ('descriptive', 'Rubric with descriptions only'), ('guide', 'Marking guide')], default='scored', max_length=12)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='rubrics.rubric')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='For a marking guide: what the marker looks for')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, help_text='Marking guides only', max_digits=6, null=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.rubric')),
            ],
            options={
                'ordering': ['rubric', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='rubrics.rubriccriterion')),
            ],
            options={
                'ordering': ['criterion', 'position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_points__isnull', True), ('max_points__gt', 0), _connector='OR'), name='rubric_criterion_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubriclevel',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 0)), name='rubric_level_points_not_negative'),
        ),
    ]
