# Generated by Django 5.2.17 on 2026-10-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('administrator', 'System Administrator'), ('course_admin', 'Course Administrator'), ('lecturer', 'Lecturer or Instructor'), ('student', 'Student'), ('auditor', 'Auditor'), ('dpo', 'Data Protection Officer')], max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('role_holders', models.PositiveIntegerField(help_text='How many role grants the list held when signed off')),
                ('teaching_staff', models.PositiveIntegerField(help_text='How many teaching memberships the list held when signed off')),
                ('notes', models.TextField(blank=True, help_text='What was changed or queried as a result')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
