# Generated by Django 5.2.17 on 2026-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_report_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpdevice',
            name='last_used_step',
            field=models.BigIntegerField(blank=True, help_text='The 30-second step of the last code accepted: a code is used once (ASVS 2.8.4)', null=True),
        ),
    ]
