# Generated by Django 5.2.17 on 2026-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_report_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('administrator', 'System Administrator'), ('course_admin', 'Course Administrator'), ('lecturer', 'Lecturer or Instructor'), ('student', 'Student'), ('auditor', 'Auditor'), ('dpo', 'Data Protection Officer'), ('learner', 'Open-course learner'), ('head_of_department', 'Head of Department'), ('registrar', 'Registrar')], max_length=40, unique=True),
        ),
    ]
