# Generated by Django 5.2.17 on 2026-10-05 16:38

import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
import practicals.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_contentitem_original_name'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, help_text='e.g. "Council for TVET occupational standard"', max_length=200)),
                ('version', models.CharField(default='1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', 'version'],
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='practicals.competencyframework')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('framework', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='practicals.competencyunit')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('unit', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('unit_type', models.CharField(choices=[('crop_plot', 'Crop plot'), ('livestock_unit', 'Livestock unit'), ('pond', 'Fish pond'), ('forest_stand', 'Forest stand'), ('laboratory', 'Laboratory'), ('processing_unit', 'Processing unit'), ('other', 'Other')], max_length=20)),
                ('unit_text', models.CharField(blank=True, help_text='For example: Pen 3, broilers', max_length=160)),
                ('task', models.CharField(max_length=300)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client_recorded_at', models.DateTimeField(help_text="When it was written, by the phone's clock")),
                ('status', models.CharField(choices=[('pending', 'Waiting for sign-off'), ('signed', 'Signed off'), ('returned', 'Returned for correction')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='courses.coursesite')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'logbook entries',
                'ordering': ['-work_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogbookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=practicals.uploads.evidence_name)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='practicals.logbookentry')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('observed_at', models.DateTimeField(help_text="When it was observed, by the phone's clock")),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the server received it')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_text', models.CharField(blank=True, max_length=160)),
                ('comments', models.TextField(blank=True)),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task', 'student', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('competent', 'Competent'), ('not_yet_competent', 'Not yet competent'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=20)),
                ('decided_on', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('client_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_submission_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_results', to='courses.coursesite')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personref')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='practicals.competencyunit')),
                ('evidence_observations', models.ManyToManyField(blank=True, related_name='competency_results', to='practicals.observation')),
            ],
            options={
                'ordering': ['site', 'student', 'unit__position'],
            },
        ),
        migrations.CreateModel(
            name='ObservationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=practicals.uploads.evidence_name)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='practicals.observation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='practicals.competencyelement')),
            ],
            options={
                'verbose_name_plural': 'performance criteria',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentCompetencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performance_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_maps', to='practicals.performancecriterion')),
            ],
            options={
                'ordering': ['site', 'assignment_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticalAssessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text='For example: farm manager, poultry unit', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personref')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_assessors', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site', 'person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PracticalCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('pass_fail', 'Pass or fail'), ('scored', 'Scored from 0')], default='pass_fail', max_length=10)),
                ('max_score', models.PositiveSmallIntegerField(default=1, help_text='1 for pass or fail')),
                ('pass_score', models.PositiveSmallIntegerField(default=1, help_text='The least score that counts as a pass')),
                ('is_critical', models.BooleanField(default=False, help_text='Must be passed for the task to be passed')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performance_criteria', models.ManyToManyField(blank=True, related_name='practical_criteria', to='practicals.performancecriterion')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'practical criteria',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Scored criteria only', null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='practicals.observation')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='practicals.practicalcriterion')),
            ],
            options={
                'ordering': ['criterion__position', 'criterion_id'],
            },
        ),
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('crop_plot', 'Crop plot'), ('livestock_unit', 'Livestock unit'), ('pond', 'Fish pond'), ('forest_stand', 'Forest stand'), ('laboratory', 'Laboratory'), ('processing_unit', 'Processing unit'), ('other', 'Other')], default='crop_plot', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Where it is done, for example Plot 7', max_length=160)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text="Relative weight within the site's coursework; 0 when the task does not count", max_digits=5)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='After this a student with no observation counts as missed', null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='First attempt and re-assessments')),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_tasks', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['closes_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='practicalcriterion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='practicals.practicaltask'),
        ),
        migrations.AddField(
            model_name='observation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='practicals.practicaltask'),
        ),
        migrations.CreateModel(
            name='SiteFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='practicals.competencyframework')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_frameworks', to='courses.coursesite')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=300)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.AddConstraint(
            model_name='logbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0), ('hours__lte', 24)), name='logbook_hours_in_a_day'),
        ),
        migrations.AddConstraint(
            model_name='logbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='logbook_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='logbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='logbook_longitude_range'),
        ),
        migrations.AlterUniqueTogether(
            name='competencyresult',
            unique_together={('site', 'student', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='performancecriterion',
            unique_together={('element', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentcompetencymap',
            unique_together={('assignment_id', 'performance_criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='practicalassessor',
            unique_together={('site', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='observationresult',
            unique_together={('observation', 'criterion')},
        ),
        migrations.AddConstraint(
            model_name='practicaltask',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='practical_task_weight_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='practicaltask',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='practical_task_one_attempt'),
        ),
        migrations.AddConstraint(
            model_name='practicaltask',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='practical_task_window_order'),
        ),
        migrations.AddConstraint(
            model_name='practicalcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gte', 1)), name='practical_criterion_max_score'),
        ),
        migrations.AddConstraint(
            model_name='practicalcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('pass_score__gte', 1), ('pass_score__lte', models.F('max_score'))), name='practical_criterion_pass_score'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='observation_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='observation_longitude_range'),
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('task', 'student', 'attempt')},
        ),
        migrations.AlterUniqueTogether(
            name='siteframework',
            unique_together={('site', 'framework')},
        ),
    ]
