# Generated by Django 5.2.17 on 2026-10-06 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_coursesite_kind_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('notice_version', models.PositiveIntegerField(blank=True, help_text='The privacy notice shown and accepted when registering', null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.coursesite')),
                ('user', models.ForeignKey(blank=True, help_text='Once made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-asked_at'],
                'indexes': [models.Index(fields=['source_ip', 'asked_at'], name='openreg_ip_at'), models.Index(fields=['email', 'asked_at'], name='openreg_email_at')],
            },
        ),
    ]
