#!/usr/bin/env python3
"""THIRD-PARTY-NOTICES for a release (item 7.20), written from the software bills of materials.

CI makes two CycloneDX bills of materials for each release: one for the Python packages the API ships
(cyclonedx-py, from an environment holding api/requirements.txt only) and one for the web packages
(@cyclonedx/cyclonedx-npm, production dependencies only). This script reads both, with the licence policy
(scripts/licence-policy.json), and writes one notices file: every component, its version and licence, and
for each component taken under a named LGPL or MPL exception (ADR 0002) where its source code is obtained,
as those licences require.

    python scripts/third_party_notices.py sbom-python.cdx.json sbom-web.cdx.json -o THIRD-PARTY-NOTICES.md

Standard library only. Exit status 1 when a component under an LGPL or MPL licence has no named exception
with a source, so a release can never ship one without saying where its source is.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POLICY_FILE = ROOT / "scripts" / "licence-policy.json"
WEAK_COPYLEFT = re.compile(r"\b(LGPL|MPL)\b|Lesser General Public|Mozilla Public", re.I)


def licences_of(component: dict) -> str:
    """The component's licence as the bill of materials gives it: an expression, identifiers or names."""
    found = []
    for entry in component.get("licenses", []):
        if "expression" in entry:
            found.append(entry["expression"])
            continue
        licence = entry.get("license", {})
        found.append(licence.get("id") or licence.get("name") or "")
    found = [f for f in found if f]
    return " AND ".join(dict.fromkeys(found)) if found else "Not stated"


def components(path: Path, ecosystem: str) -> list[dict]:
    bom = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for component in bom.get("components", []):
        name = component.get("name", "")
        if component.get("group"):
            name = f"{component['group']}/{name}"
        rows.append(
            {
                "ecosystem": ecosystem,
                "name": name,
                "version": component.get("version", ""),
                "licence": licences_of(component),
                "purl": component.get("purl", ""),
            }
        )
    return sorted(rows, key=lambda r: r["name"].lower())


def _key(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def build(python: list[dict], web: list[dict], policy: dict) -> tuple[str, list[str]]:
    """The notices as Markdown, and the problems (weak-copyleft components with no named source)."""
    exceptions = {
        ("python", _key(n)): e for n, e in policy.get("exceptions", {}).get("python", {}).items()
    } | {("npm", _key(n)): e for n, e in policy.get("exceptions", {}).get("npm", {}).items()}
    problems, sources = [], []
    for row in python + web:
        if not WEAK_COPYLEFT.search(row["licence"]):
            continue
        exception = exceptions.get((row["ecosystem"], _key(row["name"])))
        if exception is None or not exception.get("source"):
            what = f"{row['name']} {row['version']} ({row['licence']})"
            problems.append(f"{what} has no named exception with a source")
            continue
        sources.append((row, exception))

    lines = [
        "# Third-party notices",
        "",
        "The GSA LMS is built on the open-source components below. Each is used under the licence named, and",
        "each licence's full text is in the component's own distribution. The software bills of materials",
        "(CycloneDX) published with this release list the same components with their package URLs.",
        "",
        "Generated by scripts/third_party_notices.py from the bills of materials and",
        "scripts/licence-policy.json (docs/adr/0002-licence-policy.md). Do not edit by hand.",
        "",
        "## Components under the LGPL or the MPL, and where their source is obtained",
        "",
    ]
    if not sources:
        lines.append("None.")
    for row, exception in sources:
        lines += [
            f"- **{row['name']} {row['version']}** ({row['licence']}). {exception.get('reason', '')}",
            f"  Source: {exception['source']}",
        ]
    parts = (("Python packages shipped in the API", python), ("Web packages shipped in the app", web))
    for title, rows in parts:
        lines += ["", f"## {title}", "", "| Component | Version | Licence |", "|---|---|---|"]
        lines += [f"| {r['name']} | {r['version']} | {r['licence']} |" for r in rows]
    return "\n".join(lines) + "\n", problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("python_bom", type=Path)
    parser.add_argument("web_bom", type=Path)
    parser.add_argument("-o", "--output", type=Path, default=Path("THIRD-PARTY-NOTICES.md"))
    parser.add_argument("--policy", type=Path, default=POLICY_FILE)
    args = parser.parse_args(argv)
    policy = json.loads(args.policy.read_text(encoding="utf-8"))
    text, problems = build(components(args.python_bom, "python"), components(args.web_bom, "npm"), policy)
    args.output.write_text(text, encoding="utf-8")
    for problem in problems:
        print(f"third-party notices: {problem}", file=sys.stderr)
    print(f"Wrote {args.output} ({text.count(chr(10))} lines).")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
