# Generated by Django 5.2.17 on 2026-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_insert_only_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.CharField(blank=True, help_text='Why the change was made, as given', max_length=300),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='subject',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
