# Generated by Django 5.2.17 on 2026-10-05 10:00, then given the step that seals the rows already written.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seal(apps, schema_editor):
    """Chain the rows written before this migration, oldest first. The insert-only trigger is switched off
    for this one transaction, by the table's owner, and on again before it commits."""
    if schema_editor.connection.vendor != "postgresql":
        return
    AuditLog = apps.get_model("audit", "AuditLog")
    if not AuditLog.objects.exists():
        return
    from audit.chain import link

    schema_editor.execute("ALTER TABLE audit_auditlog DISABLE TRIGGER audit_log_no_update_delete")
    previous = ""
    for row in AuditLog.objects.order_by("id").iterator(2000):
        previous = link(previous, row)
        AuditLog.objects.filter(pk=row.pk).update(chain=previous)
    schema_editor.execute("ALTER TABLE audit_auditlog ENABLE TRIGGER audit_log_no_update_delete")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_subject_and_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='chain',
            field=models.CharField(default='', editable=False, help_text='Keyed fingerprint of this row and the one before', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.RunPython(seal, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AuditCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveIntegerField()),
                ('intact', models.BooleanField()),
                ('last_id', models.BigIntegerField(blank=True, null=True)),
                ('last_chain', models.CharField(blank=True, max_length=64)),
                ('first_broken_id', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
            },
        ),
    ]
