# Generated by Django 5.2.17 on 2026-10-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_first_attempts'),
        ('people', '0002_personref_post_unit_supervisor_invited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.DecimalField(blank=True, decimal_places=2, help_text='Set by the lecturer', max_digits=6, null=True)),
                ('override_note', models.CharField(blank=True, max_length=300)),
                ('staff_mark', models.DecimalField(blank=True, decimal_places=2, help_text="The marker's mark when folded in", max_digits=6, null=True)),
                ('combined', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_outcome', to='assessments.submission')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviews_each', models.PositiveSmallIntegerField(default=3, help_text="How many other students' work each student reviews")),
                ('reviews_due_at', models.DateTimeField(help_text='Reviews are taken until then')),
                ('self_assessment', models.BooleanField(default=False, help_text='Each student also assesses their own work against the rubric')),
                ('peer_weight', models.DecimalField(decimal_places=2, default=0, help_text='Percent of the mark that comes from the peer mark; 0 keeps peer review as feedback only', max_digits=5)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='When the moderated reviews were shown to the students reviewed', null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review', to='assessments.assignment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1, help_text="Work 1, 2 ... in the reviewer's list")),
                ('is_self', models.BooleanField(default=False)),
                ('scores', models.JSONField(blank=True, default=list, help_text="Rubric scores, as a marker's are kept")),
                ('mark', models.DecimalField(blank=True, decimal_places=2, help_text="Scaled to the assignment's maximum", max_digits=6, null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderation', models.CharField(choices=[('counts', 'Counts'), ('left_out', 'Left out by the lecturer')], default='counts', max_length=10)),
                ('moderation_note', models.CharField(blank=True, help_text='Why it was left out', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personref')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='people.personref')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assessments.submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='peerreview.peerreviewsetup')),
            ],
            options={
                'ordering': ['setup', 'reviewer', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='peerreviewsetup',
            constraint=models.CheckConstraint(condition=models.Q(('peer_weight__gte', 0), ('peer_weight__lte', 100)), name='peer_weight_percentage'),
        ),
        migrations.AddConstraint(
            model_name='peerreviewsetup',
            constraint=models.CheckConstraint(condition=models.Q(('reviews_each__gte', 1)), name='peer_reviews_each_positive'),
        ),
        migrations.AddConstraint(
            model_name='peerreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'submission'), name='peer_review_once'),
        ),
    ]
