# Generated by Django 5.2.17 on 2026-10-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_first_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='The hand-in that was read')),
                ('words', models.TextField(blank=True, help_text='The words compared, apart by single spaces: quotations and the instructions left out')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting to be checked'), ('done', 'Checked'), ('no_text', 'No text could be read'), ('failed', 'The check could not be finished')], default='waiting', max_length=10)),
                ('overall_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Share of the words found elsewhere', max_digits=5, null=True)),
                ('notes', models.JSONField(blank=True, default=list, help_text='What could not be read, said in words, one note a line')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity', to='assessments.submission')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BigIntegerField(db_index=True)),
                ('position', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='similarity.similaritydocument')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'hash'], name='fingerprint_document_hash')],
            },
        ),
        migrations.CreateModel(
            name='SimilarityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_words', models.PositiveIntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranges', models.JSONField(default=list, help_text='[[start, end], ...] word ranges of this document')),
                ('passages', models.JSONField(default=list, help_text='[{"mine": "...", "theirs": "...", "words": 14}] longest first')),
                ('found_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='similarity.similaritydocument')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='similarity.similaritydocument')),
            ],
            options={
                'ordering': ['document', '-percent', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'other'), name='similarity_match_once')],
            },
        ),
    ]
