# Generated by Django 5.2.17 on 2026-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('training_push', 'Training completions to the HRMS'), ('marks_push', 'Coursework totals to the SRMS'), ('staff_sync', 'Staff records from the HRMS')], max_length=20)),
                ('trigger', models.CharField(default='schedule', help_text='schedule, completion or command', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='[{"ref": ..., "code": ..., "detail": ...}]')),
                ('stopped', models.CharField(blank=True, help_text='Why the run stopped early, if it did', max_length=300)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
