# Generated by Django 5.2.17 on 2026-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_integrationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrun',
            name='kind',
            field=models.CharField(choices=[('training_push', 'Training completions to the HRMS'), ('marks_push', 'Coursework totals to the SRMS'), ('staff_sync', 'Staff records from the HRMS'), ('outcome_sync', 'Learning outcomes from the SRMS course outlines'), ('competency_push', 'Competency results and outcome standings to the SRMS')], max_length=20),
        ),
    ]
