# Generated by Django 5.2.17 on 2026-10-06 15:29

import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_contentitem_video_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.FileField(blank=True, help_text='As put up; removed once the copies are made', upload_to=video.models.video_name)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('original_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting to be prepared'), ('converting', 'Being prepared'), ('ready', 'Ready'), ('failed', 'Could not be prepared')], default='waiting', max_length=12)),
                ('failure', models.TextField(blank=True, help_text='Why it could not be prepared, in words')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.FileField(blank=True, help_text='A still frame shown before playing', upload_to=video.models.video_name)),
                ('poster_size', models.PositiveBigIntegerField(default=0)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('transcription', models.CharField(choices=[('none', 'Not asked for'), ('waiting', 'Waiting'), ('working', 'Being written'), ('done', 'Written'), ('failed', 'Could not be written')], default='none', max_length=10)),
                ('transcription_failure', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.contentitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('low', 'Low (240p): least data'), ('standard', 'Standard'), ('audio', 'Sound only')], max_length=10)),
                ('file', models.FileField(upload_to=video.models.video_name)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, help_text='The whole copy, sound included', null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='video.video')),
            ],
            options={
                'ordering': ['video', 'quality'],
                'constraints': [models.UniqueConstraint(fields=('video', 'quality'), name='video_rendition_once')],
            },
        ),
        migrations.CreateModel(
            name='CaptionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', help_text='A language tag: en, es, pt', max_length=12)),
                ('label', models.CharField(default='English', max_length=60)),
                ('text', models.TextField(help_text='WebVTT')),
                ('source', models.CharField(choices=[('uploaded', 'Put up as a file'), ('edited', 'Written or corrected in the LMS'), ('transcribed', "Written by speech recognition on GSA's server")], default='uploaded', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='video.video')),
            ],
            options={
                'ordering': ['video', 'language'],
                'constraints': [models.UniqueConstraint(fields=('video', 'language'), name='caption_once_per_language')],
            },
        ),
    ]
